### ISSUE TITLE
Disable while Ctrl key is pressed

### ISSUE THREAD

**Issue by exclipy** [ZitRos/tab-slider#1]
Sometimes, I'm hunting through my tabs with Ctrl-{Tab, Tab, Tab}.  If I take longer than 1 second looking at a tab to decide if it's the one I want, it'll slide to the front even if I don't want it.  I'd rather it not slide until I release the Ctrl button, because that would be indication that I'm actually using the tab.

**Comment by nikitaeverywhere** [comment]
@exclipy, thank you for this hint! It definitely makes sense, as personally I am struggling with this behavior too.

I’ll check whether browser APIs allow to do this and will definitely implement it. I think it is also worth to be the default behavior, while I’ll leave it configurable.

**Comment by nikitaeverywhere** [comment]
@exclipy,

So yes, possibly I didn't manage to implement this behavior because browser APIs are restrictive on keyboard events. Otherwise, this extension will have to inject content scripts into every page which would listen for Ctrl keydown/keyup events. This, in turn, would require adding an additional permission "This extension can read and change all your data on the websites you visit", not to mention it can interfere with some web apps which cancel event propagation at some point.

The possible workaround, but not a complete solution is to for example give a tab more time to stay (f.e. 2 seconds instead of default 1) in extension settings and quickly switch the tab back and forth if you don't want it to slide but still want to stay on it.

What do you think?

**Comment by exclipy** [comment]
Yeah, that's what I concluded too when I tried to implement it. Maybe
better would be to have a command to manually invoke the slide (eg.
Ctrl-`), so the user can have a longer delay while having control over when
the slide happens.

**Comment by nikitaeverywhere** [comment]
@exclipy, good point. However, it seems that regarding commands, there's only `onCommand` trigger we can listen to. In other words, again, no "keyup" behavior...

**Comment by nikitaeverywhere** [comment]
Closed due to browser API limitations that don't allow this particular feature to be implemented.
